name: jane_app
description: "تطبيق جين للدردشة والغرف الصوتية"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # أضفنا مكتبة جوجل للذكاء الاصطناعي (إذا كانت الدردشة تعتمد عليها)
  google_generative_ai: ^0.4.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
